version: '3.8'

services:

  backend:    
    image: 'petbackend'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development    
      - DB_CONNECTION_STRING=Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=password
    ports:
     - "5001:80"
    depends_on:
     - "postgres"    

  postgres:    
    image: postgres
    environment:      
      POSTGRES_PASSWORD: password    

  frontend:    
    image: belovnow/petwallet-frontend
    environment:      
      NODE_ENV: production
    ports:
     - "3000:3000"
    